[logging]
dirpath = "logs"
filename = "eflycode.log"
level = "DEBUG"
format = "{time:YYYY-MM-DD HH:mm:ss} | {level} | {file}:{function}:{line} | {message}"
rotation = "10 MB"
retention = "14 days"
encoding = "utf-8"

[model]
default = "ep-20250327150955-48bsn"

[[model.entries]]
model = "ep-20250327150955-48bsn"
name = "DeepSeek-V3 0324"
provider = "openai"
api_key = "b780d248-7a4e-47f9-b148-d31373a90bce"
base_url = "https://ark.cn-beijing.volces.com/api/v3"
max_context_length = 64000
temperature = 0.2
supports_native_tool_call = true
